sudo: false
language: python

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

script:
  - pip install .
  - lxmlproc --output ERA2010_journal_title_list.xml era_journal_list_2010_tidy.xsl ERA2010_journal_title_list.xml.orig
  - diff -uw ERA2010_journal_title_list.xml.orig ERA2010_journal_title_list.xml || true # force exit code 0
